cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart"),
    path("add/<int:product_id>", views.add_product, name="add_to_cart"),
    path("cart_product_update/<str:action>/<int:product_id>/<int:item_id>", views.cart_product_update, name="cart_product_update"),
    path('cart/<int:item_id>',views.deleteProduct,name='delete'),
    path("checkout/", views.checkout, name="checkout"),
    ]

main/urls.py
from django.urls import path 
from . import  views

app_name = "main"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home" ),
    path("about/", views.About.as_view(), name="about" ),
    path('result', views.result_page , name = 'result'),
    path('category', views.category, name = 'category'),
    path("contact/", views.Contact.as_view(), name="contact" ),
    path("detail/<slug:slug>", views.product_detail, name="detail" ),
    path("wishlist/", views.WishListView.as_view(), name="wishlist" ),
    path("wishlist/add/<int:product_id>", views.add_wishlist, name="add_wishlist" ),
]

store/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("cart/", include("cart.urls", namespace="cart")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from main.models import Product
# Create your models here.

class CartProducts(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    
    def __str__(self):
        return self.product.name

class Cart(models.Model):
    products = models.ManyToManyField(CartProducts)
    total_quantity = models.PositiveSmallIntegerField(default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    
    def __str__(self):
        return f"Cart id = {self.id}"
    
    
    def add(self, product_id):
        product = Product.objects.get(id=product_id)

        # Check if the product is already in the cart
        cart_product = self.products.filter(product=product).first()
        
        if cart_product is None:
            # Product not in cart, create a new entry
            self.products.create(
                product=product,
                quantity=1,
                price=product.get_discount_price()
            )
            self.total_quantity += 1
            self.total_price += product.get_discount_price()
        else:
            # Product already in cart, update the existing entry
            cart_product.quantity += 1
            cart_product.price += product.get_discount_price()
            cart_product.save()
            self.total_quantity += 1
            self.total_price += product.get_discount_price()

        self.save()
        return True


    def cart_product_update(self,action,product_id,item_id):
        product = Product.objects.get(id=product_id)
        obj = self.products.get(id=item_id) 
        if action == "plus":
            self.total_price += obj.product.get_discount_price()
            self.total_quantity += 1
            obj.quantity += 1
            obj.price += obj.product.get_discount_price()
            obj.save() # CartProduct.save()
            self.save() # Cart.save()
        else:
            self.total_price -= obj.product.get_discount_price()
            self.total_quantity -= 1
            obj.quantity -= 1
            obj.price -= obj.product.get_discount_price()
            obj.save() # CartProduct.save()
            self.save() # Cart.save()



class Order(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    phone  = models.CharField(max_length=250)
    city = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

cart/views.py
import telebot
from django.shortcuts import render,redirect
from django.views.generic import View
from main.models import Product
from django.contrib import messages
from .models import Cart,CartProducts,Order
from main.models import Category

bot = telebot.TeleBot("7412220605:AAEQD6X_F57VqQso2e8Kbd1yu1MHn06fW_M")
group_id = -1002028217344


def cart_init(request):
    try:
        cart = Cart.objects.get(id=request.session.get('user_cart_id'))
    except:
        cart = Cart.objects.create() # yangi cart object hosil qilish
        request.session['user_cart_id'] = cart.id
    return cart


# Create your views here.
class CartView(View):
    
    def get(self, request):
        cart = cart_init(request)
        category = Category.objects.all()
        return render(request, "cart.html",{"cart":cart,'categories':category})

def add_product(request, product_id):
    cart = cart_init(request)
    cart.add(product_id)
    return redirect("/cart/")

def cart_product_update(request,action,product_id,item_id):
    cart = cart_init(request)
    item = CartProducts.objects.get(id=item_id)
    if item.quantity == 1 and action == "minus":
        return redirect("/cart/")
    else:
        cart.cart_product_update(action,product_id,item_id)
    return redirect("/cart/")


def deleteProduct(request,item_id):
    product = CartProducts.objects.get(id=item_id)
    cart = cart_init(request)
    cart.total_price -= product.price
    cart.total_quantity -= product.quantity
    cart.save()
    product.delete()
    print(product)
    return redirect('/cart/')    


def checkout(request):
    cart = cart_init(request)
    category = Category.objects.all()
    if request.method == "POST":
        user_cart = Cart.objects.get(id=int(request.POST.get("cart_id")))
        phone = request.POST.get("phone")
        city = request.POST.get("city")
        street = request.POST.get("street")
        address = request.POST.get("address")
        if all([user_cart,phone,city,street,address]):
            Order.objects.create(cart=user_cart,phone=phone,city=city,street=street,address=address)
            text = f"""<b>Buyurtma bor !</b>\nTelefon : {phone}\nManzil : {city} {street} {address}\nTovar umumiy summa: {user_cart.total_price}"""
            bot.send_message(group_id,text,parse_mode="html")
            messages.success(request,"Sizning buyurtmangiz qabul qilindi !")
            return redirect("/cart/")
    return render(request, "checkout.html", {"cart":cart,'categories':category})

templates/about.html
{% extends "base.html" %}
{% load static %}


{% block content %}


      <div class="container py-5">
        <div class="cards w-100 p-4 mt-4">
            <h3>Условия сервиса</h3>
            <p>Задача организации, в особенности же курс на социально-ориентированный национальный проект требует от нас системного анализа модели развития! Таким образом, постоянное информационно-техническое обеспечение нашей деятельности требует от нас анализа системы масштабного изменения ряда параметров! С другой стороны социально-экономическое развитие напрямую зависит от всесторонне сбалансированных нововведений?</p>
        </div>
        <div class="cards w-100 p-4 mt-4">
            <h3>Условия доставки</h3>
            <p>Задача организации, в особенности же курс на социально-ориентированный национальный проект требует от нас системного анализа модели развития! Таким образом, постоянное информационно-техническое обеспечение нашей деятельности требует от нас анализа системы масштабного изменения ряда параметров! С другой стороны социально-экономическое развитие напрямую зависит от всесторонне сбалансированных нововведений?</p>
        </div>
        <div class="cards w-100 p-4 mt-4">
            <h3>Условия возврата</h3>
            <p>Задача организации, в особенности же курс на социально-ориентированный национальный проект требует от нас системного анализа модели развития! Таким образом, постоянное информационно-техническое обеспечение нашей деятельности требует от нас анализа системы масштабного изменения ряда параметров! С другой стороны социально-экономическое развитие напрямую зависит от всесторонне сбалансированных нововведений?</p>
        </div>
      </div>





{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Qpick</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

  </head>
  <body>




    <nav class="navbar navbar-expand-lg bg-white rounded" aria-label="Thirteenth navbar example">
      <div class="container-fluid">
          <a class="navbar-brand col-lg-3 p-3" href="/">
            <img src="{% static 'img/QPICK.png' %}" alt="" class="img-fluid"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample11" aria-controls="navbarsExample11" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse d-lg-flex" id="navbarsExample11">
          <ul class="navbar-nav col-lg-6 justify-content-lg-center">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:about' %}">about</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'main:contact' %}">contact</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Category</a>
              <ul class="dropdown-menu">
                {% for category in categories %}
                <li><a class="nav-link p-2 text-center float-start" name = 'category'  class="dropdown-item"  href="{% url 'main:category' %}?category={{ category.name }}">{{category.name}}</a></li>
                {% endfor %}
              </ul>
            </li>
          </ul>
          <form action="{% url 'main:result' %}" class="d-flex col-lg-3 gap-2 justify-content-lg-end" >
              <input type="text" class="form-control" maxlength="120" minlength="3"  name="query" placeholder="Search">
              <button class="btn btn-primary">search</button>
          </form>
          <div class="d-flex p-3 gap-3 text-dark">
            <a href="{% url 'main:wishlist' %}">
              <i class="fa-solid fa-heart fs-4 text-dark"></i>
            </a>
            <a href="{% url 'cart:cart' %}" class="
             text-decoration-none text-dark">
  
              <i class="fa-solid fa-cart-shopping fs-4 "></i>
              <sup class="w-100 fs-4 "  style="color: red;">{{cart.total_quantity}}</sup>
            </a>
          </div>
        </div>
      </div>
    </nav>
    {% if messages %}
    <div style="max-width: 33%; margin: 20px auto;">
        {% for message in messages %}
        <div {% if message.tags %} class=" alert alert-{{ message.tags }} fw-bold fs-5"{% endif %}>
          <span role='button' class="float-end" onclick="this.parentElement.style.display = 'none'">X</span>
          {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
{% block content %}
{% endblock content %}

<div class="container pt-5">
    <footer class="footer bg-white">
      <div class="row p-lg-5 rounded-top">
        <div class="col-md-3 col-lg-3">
          <img src="./img/QPICK.png" class="img-fluid p-3" alt="">
        </div>
        <div class="col-md-3 col-lg-3">
          <div class="p-3">
          <p>Избранное</p>
          <p>Корзина</p>
          <p>Контакты</p>
        </div>
          </div>
          <div class="col-md-3 col-lg-3">
            <p class="p-3">Условия сервиса</p>
            <div class="d-flex gap-3 p-3">
              <i class="fa-solid fa-globe fs-5 py-1"></i>
              <p>Каз</p>
              <p>Рус</p>
              <p>Eng</p>
            </div>
            </div>
            <div class="col-md-3 col-lg-3">
              <div class="fs-lg-2 fs-4 gap-3 d-flex p-3">
                <i class="fa-brands fa-vk"></i>
                <i class="fa-brands fa-instagram"></i>
                <i class="fa-brands fa-telegram"></i>
                <i class="fa-brands fa-whatsapp"></i>
              </div>
        </div>
          </div>
  
  </footer>
  </div>
  
  
    {% if "cart" in request.path %}
      <script src="{% static 'js/cart.js' %}"></script>
    {% endif %}
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
  </html>

templates/cart.html
{% extends "base.html" %}
{% load static %}


{% block content %}

  {% if cart.products.all %}
    <div class="container p-5">
      <div class="row">
        <div class="col-sm-12 col-md-8">
          {% for product in cart.products.all %}
          <div class="cards my-2">
            <a href="{% url 'cart:delete'  product.id %}"><i class="fa-solid fa-trash float-end p-3 fs-4 text-danger"></i></a>
            <div class=" d-flex flex-wrap align-items-center">
                <img src="{{product.product.image.url}}" class="img-fluid p-3" style="width:100px;object-fit:contain" alt="">
                <div class="body p-3"><h3>{{product.product.name|truncatewords:5}}</h3>
                  <h6>${{product.product.get_discount_price}}</h6>
                </div>
                <div class="d-flex px-lg-5 px-2">
                  <a href="{% url 'cart:cart_product_update' 'minus' product.product.id product.id %}" class="counter-minus btn btn-outline-danger p-3 px-4 rounded-5">-</a>
                    <h3 class="counter-display px-3">{{product.quantity}}</h3>
                  <a href="{% url 'cart:cart_product_update' 'plus' product.product.id product.id %}" class="counter-plus btn btn-outline-success  p-3 px-4 rounded-5">+</a>
                </div>
                <h4 class="p-3 px-lg-5">${{product.price}}</h4>
                </div>
        </div>

        {% endfor %}
    </div>

    <div class="col-sm-12 col-md-4">
        <div class="cards p-3 mt-3">
          <div class="d-flex justify-content-between">
            <h4>ИТОГО</h4>
            <h5>${{cart.total_price}}</h5>
          </div>
          <a href="{% url 'cart:checkout' %}">
          <button class="btn btn-outline-dark w-100">Перейти к оформлению</button>   
          </a>    
        </div>
    </div>
      </div>

    </div>
{% else %}


    <div class="container p-5">
        <div class="row">
            <div class="col-lg-12">
                <center>
                    <div class="">
                        <img src="{% static './img/Illustration.png' %}" class="img-fluid" alt="">
                        <h3>Корзина пуста</h3>
                        <p>Но это никогда не поздно исправить :)</p>
                        <a href="{% url 'main:home' %}" class="text-decoration-none ">
                            <div class="btn btn btn-outline-dark w-25 mt-3">В каталог товаров</div>
                        </a>
                    </div>
                </center>
            </div>
        </div>
    </div>

    {% endif %}
    

      {% endblock content %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    


<div class="container-fluid p-3 p-lg-5">
    <div class="row">
        {% for i in objects %}
        <div class="col-sm-12 col-md-4">
        <div class="cards mb-3" >
            <div class="row g-0">
              <div class="col-md-4">
                <img src="{{i.image.url}}" class="img-fluid rounded p-3" alt="...">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title p-3">{{i.name}}</h5>
                  <p class="card-text">{{i.description|truncatewords:20}}</p>
                  <p class="card-text"><small class="text-muted">{{i.price}}</small></p>
                </div>
              </div>
            </div>

    </div>
    </div>
    {% endfor %}
</div>
</div>


{% endblock %}

templates/detail.html
{% extends "base.html" %}
{% block content  %}


    <div class="container py-5">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="cards bg-white p-3 mt-3 mt-lg-5">
                    {% if object.id in request.session.wishlist %}
                    <a href="{% url 'main:add_wishlist' object.id %}">
                      <i class="fa-solid fa-heart fs-4 text-info"></i>
                    </a>
                  {% else %}
                    <a href="{% url 'main:add_wishlist' object.id %}">
                      <i class="fa-regular fa-heart fs-4 text-info"></i>
                    </a>
                  {% endif %}
                      <center>
                      <img src="{{object.image.url}}" class="img-fluid" style="height: 500px!important;object-fit: contain;" alt="{{object.name}}">
                      </center>
                      <div class="d-flex py-3 gap-2 justify-content-between">
                        <h3 class="">{{object.name}}</h3>
                        <div class="d-flex gap-3 py-3">
                        <h2 class="text-warning m-0">${{object.get_discount_price}}<h2>
                        <h3 class="text-warning m-0 text-decoration-line-through">${{object.price}}<h3>
                        <h4>-{{object.discount}}%</h4>
                        </div>
                      </div>
                      <a href="" class="text-warning text-decoration-none fs-5"> <i class="fa-solid fa-star"></i> 4.5 </a>
                    </div>
            </div>
            <div class="col-sm-12 col-md-9">
                <div class="cards mt-3 bg-body-tertiary">

                    <div class="bg-white cards p-3 ">
                        <h3>Описание и характеристики</h3>
                    </div>
                
                <div class="card-body p-3">
                    <p class="card-text">
                      {{object.description}}
                   </p>
                </div>
                </div>

            </div>

            <div class="col-sm-12 col-md-3">
                <div class="p-3 mt-3 bg-white cards">
                <a href="{% url 'cart:add_to_cart' object.id  %}" class="btn btn btn-outline-dark w-100 mt-3">
                  <i class="fa-solid fa-cart-shopping"></i>
                  Добавить в корзину
                </a>
                
            </div>
            </div>

            <div class="col-sm-12 col-md-12 my-3">
              <br>
                <h2>Add a Comment</h2>
                <br>
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="text" max_length="150" min_length="3" class="form-control" placeholder="User" name="user">
                    <br>
                    <textarea class="form-control" placeholder="Add comment" min_length="10" minlength="3"  max_length="255" name="body" id="" cols="30" rows="10"></textarea>
                    <br>
                    <input class="btn btn-primary" type="submit" value="comment">
                </form>
                <br>
                <h2>Comments</h2>
                <br>
                {% for rating in ratings %}
                <div class="cards p-3 my-3">
                    <div>
                        <strong>Comment by {{ rating.name }}
                        <p>{{ rating.comment }}</p>
                        
                    </div>
                </div>
                {% endfor %}
            </div>
            </div>

        </div>
    </div>





    {% endblock content  %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
      


<div class="container">
<div id="carouselExampleIndicators" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active banner">
      <div class="banner">
            <h3 class="p-3">Аксессуары для iPhone 13 Pro Max</h3>
            <img src="{% static 'img/13.png' %}" class="img-fluid me-3 me-lg-5">
      </div>
    </div>
    <div class="carousel-item banner">
      <div class="banner">
        <h3 class="p-3">Аксессуары для iPhone 13 Pro Max</h3>
        <img src="{% static 'img/13.png' %}" class="img-fluid me-3 me-lg-5">
      </div>
    </div>
    <div class="carousel-item banner">
      <div class="banner">
        <h3 class="p-3">Аксессуары для iPhone 13 Pro Max</h3>
        <img src="{% static 'img/13.png' %}" class="img-fluid me-3 me-lg-5">
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>


    </div>


    <div class="container py-5">
        <div class="row">
          <h4 class="text-info">Чехлы</h4>
          
          {% for case in cases  %}
            
            
            <div class="col-sm-12 col-md-4">
                <div class="cards bg-white p-3 mt-3">
                  {% if case.id in request.session.wishlist %}
                  <a href="{% url 'main:add_wishlist' case.id %}">
                    <i class="fa-solid fa-heart fs-4 text-info"></i>
                  </a>
                {% else %}
                  <a href="{% url 'main:add_wishlist' case.id %}">
                    <i class="fa-regular fa-heart fs-4 text-info"></i>
                  </a>
                {% endif %}
                    <center>
                      <a href="{% url 'main:detail' case.slug %}">
                    <img src="{{case.image.url}}" class="img-fluid" alt="">
                      </a>
                    <h3>Стеклянные</h3>
                    </center>
                    <!-- <h4>Стеклянные</h4> -->
                  </div>
            </div>
          {% endfor %}
    </div>
    </div>



    <div class="container py-5">
      <div class="row">
        <h4 class="text-info">Чехлы</h4>
        {% for product in object_list %}
          <div class="col-sm-12 col-md-6 col-lg-4">

              <div class="cards bg-white p-3 mt-3 mt-lg-5">
                {% if product.id in request.session.wishlist %}
                  <a href="{% url 'main:add_wishlist' product.id %}">
                    <i class="fa-solid fa-heart fs-4 text-info"></i>
                  </a>
                {% else %}
                  <a href="{% url 'main:add_wishlist' product.id %}">
                    <i class="fa-regular fa-heart fs-4 text-info"></i>
                  </a>
                {% endif %}
                  <center>
                 <a href="{% url 'main:detail' product.slug %}">
                  <img src="{{product.image.url}}" class="img-fluid" height="290" style="height: 290px!important;object-fit: contain;" alt="{{product.name}}">
                 </a>
                  </center>
                  <div class="d-flex py-3 gap-2 justify-content-between flex-column">
                  <h5 class="">{{product.name}}</h5>
                  <div class="d-flex gap-2 justify-content-between  ">
                    <h5 class="text-warning m-0">${{product.get_discount_price}}<h5>
                    <h6 class="text-warning m-0 text-decoration-line-through">
                      ${{product.price}}
                    </h6>
                    <h6>-{{product.discount}}%</h6>
                    <a href="" class="text-warning text-decoration-none fs-5"> 
                      <i class="fa-solid fa-star"></i> {{product.rating}} </a>
                  </div>
                 
                </div>
                 
                </div>



          </div>
          {% endfor %}
      </div>

    </div>
    <div class="container py-5">
      <div class="row">
        <h4 class="text-info">Наушники  умные часы</h4>
        {% for product in headphones %}
          <div class="col-sm-12 col-md-6 col-lg-4">

              <div class="cards bg-white p-3 mt-3 mt-lg-5">
                {% if product.id in request.session.wishlist %}
                <a href="{% url 'main:add_wishlist' product.id %}">
                  <i class="fa-solid fa-heart fs-4 text-info"></i>
                </a>
              {% else %}
                <a href="{% url 'main:add_wishlist' product.id %}">
                  <i class="fa-regular fa-heart fs-4 text-info"></i>
                </a>
              {% endif %}
                  <center>
                    <a href="{% url 'main:detail' product.slug %}">
                  <img src="{{product.image.url}}" class="img-fluid" style="height: 290px!important;object-fit: contain;" alt="{{product.name|truncatewords:10}}">
                </a>
                  </center>
                  <div class="d-flex py-3 gap-2 justify-content-between">
                  <h5 class="">{{product.name}}</h5>
                  <div class="">
                  <h5 class="text-warning m-0">${{product.get_discount_price}}<h5>
                  <h6 class="text-warning m-0 text-decoration-line-through">${{product.price}}<h6>
                  </div>
                  <h6>-{{product.discount}}%</h6>
                </div>
                  <a href="" class="text-warning text-decoration-none fs-5"> 
                    <i class="fa-solid fa-star"></i> {{product.rating}} </a>
                </div>



          </div>
          {% endfor %}
      </div>

    </div>



  </div>

{% endblock %}

templates/liked_product.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="container py-5">

  <div class="row">
    <h4 class="text-info">Liked</h4>
    {% for product in object_list %}
    <div class="col-sm-12 col-md-6 col-lg-4">
        <div class="cards bg-white p-3 mt-3 mt-lg-5">
          {% if product.id in request.session.wishlist %}
            <a href="{% url 'main:add_wishlist' product.id %}">
              <i class="fa-solid fa-heart fs-4"></i>
            </a>
          {% else %}
            <a href="{% url 'main:add_wishlist' product.id %}">
              <i class="fa-regular fa-heart fs-4"></i>
            </a>
          {% endif %}
            <center>
           <a href="{% url 'main:detail' product.slug %}">
            <img src="{{product.image.url}}" class="img-fluid" style="height: 290px!important;object-fit: contain;" alt="{{product.name}}">
           </a>
            </center>
            <div class="d-flex py-3 gap-2 justify-content-between flex-column">
            <h5 class="">{{product.name}}</h5>
            <div class="d-flex gap-2 justify-content-between  ">
              <h5 class="text-warning m-0">${{product.get_discount_price}}<h5>
              <h6 class="text-warning m-0 text-decoration-line-through">
                ${{product.price}}
              </h6>
              <h6>-{{product.discount}}%</h6>
              <a href="" class="text-warning text-decoration-none fs-5"> 
                <i class="fa-solid fa-star"></i> {{product.rating}} </a>
            </div>
           
          </div>
           
          </div>



    </div>
    {% endfor %}
  </div>
    

</div>


{% endblock content %}

templates/result.html
{% extends "base.html" %} 
{% load static %}


{% block content %}







<div class="container-fluid p-3 p-lg-5">
    <div class="row">
        {% for i in query %}
        <div class="col-sm-12 col-md-4">
        <div class="cards mb-3" >
            <div class="row g-0">
              <div class="col-md-4">
                <img src="{{i.image.url}}" class="img-fluid rounded p-3" alt="...">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title p-3">{{i.name}}</h5>
                  <p class="card-text">{{i.description|truncatewords:20}}</p>
                  <p class="card-text"><small class="text-muted">{{i.price}}</small></p>
                </div>
              </div>
            </div>

    </div>
    </div>
    {% endfor %}
</div>
</div>






{% endblock %}